# Generated by Django 5.1.7 on 2025-03-09 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_content_note_contents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='contents',
            new_name='content',
        ),
    ]
