# Generated by Django 5.1.7 on 2025-03-12 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_user_id_note_user_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user_ids',
            new_name='author',
        ),
    ]
