# Generated by Django 5.1.7 on 2025-03-12 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_user_ids_note_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='author',
            new_name='author_id',
        ),
    ]
