# Generated by Django 5.1.7 on 2025-03-12 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_author_note_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='author_id',
            new_name='author',
        ),
    ]
