# Generated by Django 5.1.7 on 2025-03-15 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_author_id_note_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='reated_at',
            new_name='created_at',
        ),
    ]
