# Generated by Django 5.1.7 on 2025-03-15 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_reated_at_note_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='created_at',
            new_name='reated_at',
        ),
    ]
