# Generated by Django 5.1.7 on 2025-03-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_userdetails_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to='uploads/images'),
            preserve_default=False,
        ),
    ]
