# Generated by Django 5.1.7 on 2025-03-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_userdetails_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='uploads/files'),
        ),
    ]
